version: '3.9'

services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pete
      POSTGRES_PASSWORD: hello_you
      POSTGRES_DB: top_vino_app
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://pete:hello_you@postgres:5432/top_vino_app

volumes:
  postgres_data:
