#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

REPO="Pilks-pixel/top_vino_backend"
PR_NUMBER="${1:?Usage: scripts/setup-repository-policy.sh REPRESENTATIVE_PR_NUMBER}"
[[ "$PR_NUMBER" =~ ^[1-9][0-9]*$ ]] || { echo "Expected a PR number" >&2; exit 1; }
cd "$(dirname "$0")/.."
EVIDENCE_FILE="${TMPDIR:-/tmp}/top-vino-policy-${PR_NUMBER}.json"

banner "Top Vino repository policy (dashboard fallback)"

stage "Check the current PR and CI contract"
open_url "https://github.com/$REPO/pull/$PR_NUMBER/checks"
step "Use an open PR targeting main that contains the reviewed #47 workflow."
step "Wait for literal CI / quality and CI / container jobs to finish with success."
step "Review .github/workflows/ci.yml: both jobs must be unconditional; no path filters, needs, job if, continue-on-error, provider secrets, or write permissions."
warn "GitHub accepts skipped checks. A ruleset cannot distinguish them; never accept skipped or neutral evidence."
confirm "Both jobs really ran successfully on the current PR commit?" || exit 1

stage "Set GitHub Actions trust and permissions"
open_url "https://github.com/$REPO/settings/actions"
step "Actions > General > Actions permissions: allow owner and select non-owner actions; enable only actions created by GitHub, no verified creators or patterns."
step "Enable Require actions to be pinned to a full-length commit SHA; Save. Local actions remain allowed."
step "Workflow permissions: Read repository contents and packages permissions; leave Allow GitHub Actions to create and approve pull requests unchecked; Save."
confirm "Selected GitHub/local actions, full SHA requirement, and read-only defaults are saved?" || exit 1

stage "Enable reviewed dependency updates"
open_url "https://github.com/$REPO/settings/security_analysis"
step "Settings > Advanced Security: enable Dependency graph, Dependabot alerts, and Dependabot security updates. Retain secret scanning and push protection."
step "Version updates begin after .github/dependabot.yml reaches main; keep its weekly npm, Docker, and Actions configuration."
open_url "https://github.com/$REPO/settings"
step "General > Pull Requests: disable Allow auto-merge; do not merge dependency updates automatically."
confirm "Dependabot protection is enabled and auto-merge is disabled?" || exit 1

stage "Import or reconcile the reviewed main ruleset"
open_url "https://github.com/$REPO/settings/rules"
step "If sandbox-main already exists, edit it rather than creating a duplicate. Otherwise New ruleset > Import a ruleset > select .github/policies/main-ruleset.json."
step "Review active default-branch targeting, empty bypass list, zero approvals, resolved conversations, strict exact checks from GitHub Actions, block deletion, and block force pushes."
step "Create or save the ruleset. Keep exactly one active branch ruleset; inspect any existing conflicts rather than removing them blindly."
confirm "One active reviewed ruleset is saved, with no owner bypass?" || exit 1

stage "Verify settings and owner enforcement"
open_url "https://github.com/$REPO/pull/$PR_NUMBER"
step "Read docs/repository-policy.md Live acceptance procedure. Inspect an existing pending/failed/stale PR as owner: merging must be blocked without an override. Do not attempt a real merge or direct push."
step "Confirm unresolved conversations block merging; inspect ruleset source and bypass list for owner enforcement."
confirm "Owner merge-blocking evidence has been recorded privately without merging?" || exit 1
node scripts/repository-policy.mjs capture "$REPO" "$PR_NUMBER" "$EVIDENCE_FILE"
node scripts/repository-policy.mjs verify "$EVIDENCE_FILE"
note "Saved API evidence to $EVIDENCE_FILE (contains repository metadata; keep private)."
note "Keep live criteria pending if any owner blocking or skipped-job evidence remains unverified."

finish
