#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7
ENV_FILE="${ENV_FILE:-.sandbox-operator.env}"
umask 077
banner "Top Vino disposable sandbox setup"

stage "Authorize accounts and confirm $0"
open_url "https://dashboard.render.com"
open_url "https://console.neon.tech"
step "Keep workspace and log access owner-only. Authorize only top_vino_backend."
step "Inspect billing: no Render payment method and no Neon automatic paid path."
confirm "Both accounts are incapable of automatic paid overage?" || exit 1

stage "Create the dashboard-managed Neon project"
open_url "https://console.neon.tech"
step "Create one Free project in Singapore, PostgreSQL 15; selected branch/database."
step "If PostgreSQL 15 is unavailable, stop and review the supported-major change."
ask NEON_PROJECT_NAME "Verified project name:"
ask NEON_BRANCH_NAME "Verified branch name:"
ask NEON_DATABASE_NAME "Verified database name:"
write_env NEON_PROJECT_NAME "$NEON_PROJECT_NAME"
write_env NEON_BRANCH_NAME "$NEON_BRANCH_NAME"
write_env NEON_DATABASE_NAME "$NEON_DATABASE_NAME"
confirm "Region, major and Free compute verified?" || exit 1

stage "Separate migration owner and runtime SQL role"
open_url "https://console.neon.tech"
step "Select branch -> SQL Editor. Follow docs/deployment-runbook.md role SQL."
step "Create runtime role using SQL, never console Add Role (it inherits admin)."
step "Set password privately in console; obtain pooled runtime/direct owner TLS URLs."
step "Store secret values in your private password manager; paste none here."
ask NEON_MIGRATION_ROLE "Verified migration owner role name:"
ask NEON_RUNTIME_ROLE "Verified nonowner runtime role name:"
write_env NEON_MIGRATION_ROLE "$NEON_MIGRATION_ROLE"
write_env NEON_RUNTIME_ROLE "$NEON_RUNTIME_ROLE"
confirm "Runtime privileges/default grants reviewed and endpoints distinct?" || exit 1

stage "Protected main and successful checks"
open_url "https://github.com/Pilks-pixel/top_vino_backend/settings/rules"
step "Follow docs/repository-policy.md. Review/merge draft layers in dependency order."
step "No bypass; strict PR gate; CI / quality and CI / container succeed on accepted main SHA."
step "Verify Actions SHA policy, Dependabot alerts/security/weekly updates."
confirm "Reviewed Blueprint is on protected main with both successful checks?" || exit 1

stage "Review the one-service Blueprint"
open_url "https://dashboard.render.com/select-repo?type=blueprint"
step "Select top_vino_backend; main; render.yaml. Review single Free Singapore Docker service."
step "No disk, previews, database, paid resource or extra service. Default migration entrypoint."
confirm "Creation plan matches reviewed render.yaml and budget?" || exit 1

stage "Enter secrets directly in Render and deploy"
open_url "https://dashboard.render.com"
step "Fill sync:false DATABASE_URL (pooled runtime), DIRECT_URL (direct owner), BETTER_AUTH_SECRETS."
step "Never put provider/database credentials or deploy tokens into GitHub or this wizard."
step "Confirm successful checks on initial main SHA, then Apply."
ask SANDBOX_URL "Assigned public HTTPS origin (no path/query):"
write_env SANDBOX_URL "$SANDBOX_URL"
step "Compare assigned origin to both auth/frontend values in render.yaml."
confirm "Origins match and Render shows the expected commit live?" || exit 1

stage "Prove tester smoke and operational settings"
open_url "$SANDBOX_URL/docs"
step "Provision tester privately and seed from workstation; change initial password."
step "Follow docs/release-recovery.md: identity, health, readiness, schemas, sign-in, private Deck, logs."
step "Keep TRUST_PROXY false until real-client spoof/edge tests pass."
step "Follow docs/sandbox-operations.md to enable failure-only emails, probe and quota review."
step "Record sanitized evidence; leave unverified acceptance pending. No credentials in evidence."
confirm "All first-release checks verified?" || exit 1
finish
